# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    loaders:
        default:
            filesystem:
                data_root:
                    - '%app.path.public%'

    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        admin_show:
            filters:
                thumbnail: { size: [198, 120], mode: outbound }
        pdf_progress:
            filters:
                fixed:
                    width: 351
                    height: 197
        ajax_uploader:
            filters:
                thumbnail: { size: [198, 120], mode: outbound }
                background: { size: [200, 122], position: center, color: '#000000' }